In [20]:
#imports
import pandas as pd
import numpy as np

In [21]:
# dataset files
comment_files = ['Youtube02-KatyPerry.csv','Youtube01-Psy.csv','Youtube05-Shakira.csv','Youtube04-Eminem.csv','Youtube03-LMFAO.csv']

In [22]:
# Adding dataset file's into a pandas dataframe
dfex = []
for x in comment_files:
    data = pd.read_csv(x)
    dfex.append(data)
dfex = pd.concat(dfex)
dfex.head()

COMMENT_ID        AUTHOR                 DATE  \
0      z12pgdhovmrktzm3i23es5d5junftft3f   lekanaVEVO1  2014-07-22T15:27:50   
1    z13yx345uxepetggz04ci5rjcxeohzlrtf4      Pyunghee  2014-07-27T01:57:16   
2  z12lsjvi3wa5x1vwh04cibeaqnzrevxajw00k    Erica Ross  2014-07-27T02:51:43   
3    z13jcjuovxbwfr0ge04cev2ipsjdfdurwck  Aviel Haimov  2014-08-01T12:27:48   
4  z13qybua2yfydzxzj04cgfpqdt2syfx53ms0k    John Bello  2014-08-01T21:04:03   

                                             CONTENT  CLASS  
0  i love this so much. AND also I Generate Free ...      1  
1  http://www.billboard.com/articles/columns/pop-...      1  
2  Hey guys! Please join me in my fight to help a...      1  
3  http://psnboss.com/?ref=2tGgp3pV6L this is the...      1  
4  Hey everyone. Watch this trailer!!!!!!!!  http...      1

In [4]:
# Checking for NULL values 
HAS_NULL = dfex.isnull()
ROWS_WITH_NAN = dfex[HAS_NULL.any(axis=1)]
print(ROWS_WITH_NAN)

                                      COMMENT_ID  \
0              z12rwfnyyrbsefonb232i5ehdxzkjzjs2   
2              z13vsfqirtavjvu0t22ezrgzyorwxhpf3   
4              z13xjfr42z3uxdz2223gx5rrzs3dt5hna   
6              z12zgrw5furdsn0sc233hfwavnznyhicq   
8          z12gxdortqzwhhqas04cfjrwituzghb5tvk0k   
..                                           ...   
440  LneaDw26bFv4NFg1m91sL1Aq1p-2N06VweQT4vOwTqc   
442  LneaDw26bFsVQRSG0ecctIfRIn4Od1tJqvnhDwCNqbI   
443  LneaDw26bFu3RCmyrWyP9S6wh1h9dBv3X95g1HzKAb4   
444  LneaDw26bFsD65dtIvAEObWYIYnFTqQDKBek_Ypz3J8   
445  LneaDw26bFuvs-8oWkLpAFa6g3QHpWD8k7sbbMP3Bg8   

                                 AUTHOR DATE  \
0                           Lisa Wellas  NaN   
2                            Ajkal Khan  NaN   
4                           Jihad Naser  NaN   
6                              kyeman13  NaN   
8                  Muhammad Asim Mansha  NaN   
..                                  ...  ...   
440  Ando Nesia - | MC | Music Producer

In [5]:
# Dropping unrelated columns
df = dfex.drop(['COMMENT_ID','AUTHOR','DATE'],axis=1)
df.head()

CONTENT  CLASS
0  i love this so much. AND also I Generate Free ...      1
1  http://www.billboard.com/articles/columns/pop-...      1
2  Hey guys! Please join me in my fight to help a...      1
3  http://psnboss.com/?ref=2tGgp3pV6L this is the...      1
4  Hey everyone. Watch this trailer!!!!!!!!  http...      1

In [6]:
#Again checking for NULL values
HAS_NULL2 = df.isnull()
ROWS_WITH_NAN2 = df[HAS_NULL2.any(axis=1)]
print(ROWS_WITH_NAN2)

Empty DataFrame
Columns: [CONTENT, CLASS]
Index: []


In [7]:
df.value_counts(['CLASS'])

CLASS
1        1005
0         951
dtype: int64

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['CONTENT'], df['CLASS'], random_state=0)

In [9]:
print(X_train.head(), y_train.head())

240                                   Shakira I love you
417     are  there  people who like  this shit? hahah...
81                                          Very Nice !
205    I know that maybe no one will read this but PL...
53                   WE GO FOR 1,000,000,000 FOR EMINEM
Name: CONTENT, dtype: object 240    0
417    0
81     0
205    1
53     0
Name: CLASS, dtype: int64


In [10]:
# All imports
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.naive_bayes import MultinomialNB # alpha = 0.1
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score

In [11]:
# Printing smallest and largest tfidfvalues of tokens
Wvect = TfidfVectorizer(min_df=5).fit(X_test)
t_X_train = Wvect.transform(X_test)   
sorted_tfidf_index = t_X_train.max(axis = 0).toarray()[0].argsort()
sorted_tfidf_value = np.sort(t_X_train.max(axis = 0).toarray()[0])

feature_names = np.array(Wvect.get_feature_names())
    
smallest_tfidfs = feature_names[sorted_tfidf_index[:20]]
smallest_tfidfs_vals = sorted_tfidf_value[:20] 
smallest_tfidfs_series = pd.Series(data = smallest_tfidfs_vals, index = smallest_tfidfs)
smallest_tfidfs_series = smallest_tfidfs_series.iloc[np.lexsort([smallest_tfidfs_series.index, smallest_tfidfs_series.values])]
    
    
largest_tfidfs = feature_names[sorted_tfidf_index[-20:]]
largest_tfidfs_vals = sorted_tfidf_value[-20:]
largest_tfidfs_series = pd.Series(data = largest_tfidfs_vals, index = largest_tfidfs)
largest_tfidfs_series = largest_tfidfs_series.iloc[np.lexsort([largest_tfidfs_series.index, largest_tfidfs_series.values])[::-1]]
    
print(smallest_tfidfs_series, largest_tfidfs_series)


probably      0.134032
spam          0.165381
making        0.192129
hello         0.193778
today         0.197145
month         0.206035
working       0.212071
any           0.213335
these         0.221679
nothing       0.228040
take          0.235892
anyone        0.240294
chance        0.247872
dream         0.247947
thank         0.254816
trying        0.258867
appreciate    0.260044
first         0.273844
getting       0.280303
website       0.286403
dtype: float64 wow          1.0
the          1.0
super        1.0
style        1.0
still        1.0
shakira      1.0
party        1.0
nice         1.0
lt           1.0
love         1.0
like         1.0
http         1.0
good         1.0
from         1.0
cool         1.0
but          1.0
br           1.0
billion      1.0
beautiful    1.0
awesome      1.0
dtype: float64


In [12]:
# Using Multinomial Naive bayes for classification

vect2 = TfidfVectorizer(min_df=5,ngram_range = (1,3)).fit(X_train)
t_X_train = vect2.transform(X_train)
t_X_test = vect2.transform(X_test)

model = MultinomialNB(alpha = 0.1)

model.fit(t_X_train, y_train)

pred = model.predict(t_X_test)
score = roc_auc_score(y_test,pred)
print(score)

0.9219628514056225


In [13]:
test1= ["Check out my page. Free games.", "This is so cool.", "Check my song for better version.","www.iiits.ac.in"]
vec = vect2.transform(test1)
output1 = model.predict(vec)
print(output1)

[1 0 1 1]


In [14]:
# Using Logistic Regression for classification

vect3 = TfidfVectorizer(min_df=5, ngram_range = (1,3)).fit(X_train)
    
tX_train = vect3.transform(X_train)
tX_test = vect3.transform(X_test)

model2 = LogisticRegression(C = 100)

model2.fit(tX_train, y_train)
pred2 = model2.predict(tX_test)    
score = roc_auc_score(y_test, pred2)
print(score)

0.9571536144578313


In [15]:
test1= ["Check out my page. Free games.", "This is so cool.", "Check my song for better version.","www.iiits.ac.in"]
vec = vect3.transform(test1)
output1 = model2.predict(vec)
print(output1)

[1 0 1 1]


In [16]:
# Using SVM for classification

vect4 = TfidfVectorizer(min_df=5, ngram_range = (1,3)).fit(X_train)
t_X_train2 = vect4.transform(X_train)
t_X_test2 = vect4.transform(X_test)

model3 = SVC(C=10000)
model3.fit(t_X_train2, y_train)

pred3 = model3.predict(t_X_test2)
score = roc_auc_score(y_test, pred3)
print(score)

0.9594628514056225


In [17]:
test1= ["Check out my page. Free games.", "This is so cool.", "Check my song for better version.","www.iiits.ac.in"]
vec = vect4.transform(test1)
output1 = model3.predict(vec)
print(output1)

[1 0 1 1]


Next Steps

1. Adding character ngrams.
2. Adding more features like length of comment, etc.

In [18]:
import pickle
filename = 'finalized_spam_model.sav'
pickle.dump(model2, open(filename,'wb'))

In [19]:
vect_file = 'vectorizer.sav'
pickle.dump(vect2, open(vect_file,'wb'))